name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: curl -X POST "https://api.render.com/deploy/srv-culhm9d2ng1s73asc690?key=I7WjClkzXc4"
